sudo: required
dist: trusty
language: cpp

before_install:
  - ls
  - export ROBOSCHOOL_PATH=$(pwd)
  - sudo apt-get -qq update
  - sudo apt-get install -y wine wget perl git libcommon-sense-perl
  - sudo apt-get install xvfb
  - xvfb :0 -screen 0 1024x768x16 &
  - export DISPLAY=:0.0
  - git clone https://github.com/Krakonos/msysww
  - cd msysww
  - PATH=$PATH:$(pwd):/home/travis/.msysww/drive_c/msys64:/home/travis/.msysww/drive_c/msys64/usr/bin/
  - MSYS=/home/travis/.msysww/drive_c/msys64
  - echo MSYS:${MSYS}
  - chmod +x msysww
  - msysww --init
  - cd ..
  - git clone https://github.com/olegklimov/bullet3 -b roboschool_self_collision
  - ls
  - mkdir bullet3/build
  - cd bullet3/build
  - ls ${MSYS}
  - ls /home/travis/.msysww/drive_c/msys64/usr/bin/
  - export MSYSEXEC="wine "${MSYS}"/usr/bin/mintty.exe --exec"
  - echo "MSYSEXEC:"$MSYSEXEC
  - export MSYSTEM=MSYS
  - $MSYSEXEC "pacman -S mingw-w64-x86_64-freeglut mingw-w64-x86_64-boost mingw-w64-x86_64-qt5-static mingw-w64-x86_64-bullet mingw-w64-x86_64-python3 mingw-w64-x86_64-glew mingw-w64-x86_64-SDL mingw-w64-x86_64-SDL2"
  - $MSYSEXEC "cmake -DBUILD_SHARED_LIBS=ON -DUSE_DOUBLE_PRECISION=1 -DCMAKE_INSTALL_PREFIX:PATH=$ROBOSCHOOL_PATH/roboschool/cpp-household/bullet_local_install -DBUILD_CPU_DEMOS=OFF -DBUILD_BULLET2_DEMOS=OFF -DBUILD_EXTRAS=OFF  -DBUILD_UNIT_TESTS=OFF -DBUILD_CLSOCKET=OFF -DBUILD_ENET=OFF -DBUILD_OPENGL3_DEMOS=OFF .. "
  - $MSYSEXEC "make -j4"
  - $MSYSEXEC "make install"
  - cd ../..
  - ls
  #- ROBOSCHOOL_PATH=$(pwd) &&  git clone https://github.com/olegklimov/bullet3 -b roboschool_self_collision && mkdir bullet3/build && cd bullet3/build && cmake -DBUILD_SHARED_LIBS=ON -DUSE_DOUBLE_PRECISION=1 -DCMAKE_INSTALL_PREFIX:PATH=$ROBOSCHOOL_PATH/roboschool/cpp-household/bullet_local_install -DBUILD_CPU_DEMOS=OFF -DBUILD_BULLET2_DEMOS=OFF -DBUILD_EXTRAS=OFF  -DBUILD_UNIT_TESTS=OFF -DBUILD_CLSOCKET=OFF -DBUILD_ENET=OFF -DBUILD_OPENGL3_DEMOS=OFF .. && make -j4 && make install && cd ../..
  #- sudo python3 setup.py install