before_install:
  - sudo add-apt-repository ppa:flosoft/cross-mingw -y
  - sudo apt-get -qq update
  - sudo apt-get install -y mingw-w64-x86_64-freeglut mingw-w64-x86_64-boost mingw-w64-x86_64-qt5-static mingw-w64-x86_64-bullet mingw-w64-x86_64-python3 mingw-w64-x86_64-glew mingw-w64-x86_64-SDL mingw-w64-x86_64-SDL2
